---
groups:
- name: update-dependencies
  jobs:
  - update-cf-smoke-tests
  - update-release
- name: test-and-release
  jobs:
  - claim-cats-pool
  - deploy-updated-smokes
  - run-smokes-errand
  - delete-smokes-deployment
  - create-final-release

release_lock: &release_lock_if_not_success
  on_failure: &release_lock
    put: cats-pool
    params:
      release: cats-pool
  on_error: *release_lock
  on_abort: *release_lock

resources:
- name: cf-deployment-concourse-tasks
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: runtime-ci
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/runtime-ci.git
    branch: main

- name: cf-smoke-tests-release
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/cf-smoke-tests-release.git
    branch: main
    private_key: ((ard_wg_gitbot_ssh_key.private_key))

- name: cf-smoke-tests-release-trigger
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/cf-smoke-tests-release.git
    private_key: ((ard_wg_gitbot_ssh_key.private_key))
    ignore_paths:
    - releases/**
    - .final_builds/**
    - ci/**
    - .envrc

- name: cf-smoke-tests
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/cf-smoke-tests.git
    branch: main
    private_key: ((ard_wg_gitbot_ssh_key.private_key))

- name: relint-envs
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/relint-envs.git
    private_key: ((ard_wg_gitbot_ssh_key.private_key))

- name: cats-pool
  type: pool
  icon: pool
  source:
    uri: git@github.com:cloudfoundry/relint-ci-pools
    branch: main
    pool: cats
    private_key: ((ard_wg_gitbot_ssh_key.private_key))

- name: cf-smoke-tests-version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/cf-relint-ci-semver.git
    branch: main
    private_key: ((ard_wg_gitbot_ssh_key.private_key))
    file: cf-smoke-tests-version

- name: windows2019-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-windows2019-go_agent

- name: golang-release
  type: git
  source:
    uri: https://github.com/bosh-packages/golang-release.git

jobs:
- name: update-cf-smoke-tests
  serial: true
  public: true
  serial_groups: [update-dependencies]
  plan:
  - in_parallel:
    - get: golang-release
      trigger: true
    - get: runtime-ci
    - get: cf-smoke-tests
  - task: bump-go-deps
    file: golang-release/ci/tasks/shared/bump-deps.yml
    input_mapping:
      input_repo: cf-smoke-tests
    output_mapping:
      output_repo: cf-smoke-tests
    params:
      SOURCE_PATH: .
  - put: cf-smoke-tests
    params:
      repository: cf-smoke-tests
      rebase: true

- name: update-release
  serial: true
  public: true
  serial_groups: [update-dependencies]
  plan:
  - in_parallel:
    - get: cf-smoke-tests
      trigger: true
    - get: golang-release
      trigger: true
      passed: [update-cf-smoke-tests]
    - get: runtime-ci
    - get: cf-smoke-tests-release
  - task: bump-cf-smoke-tests-submodule
    file: runtime-ci/tasks/bump-cf-smoke-tests/task.yml
    output_mapping:
      updated-cf-smoke-tests-release: cf-smoke-tests-release
  - task: bump-release-go-package
    file: golang-release/ci/tasks/shared/bump-golang-package.yml
    input_mapping:
      input_repo: cf-smoke-tests-release
    output_mapping:
      output_repo: cf-smoke-tests-release
    params:
      PACKAGES: [golang-1-linux, golang-1-windows]
      PRIVATE_YML: |
        ---
        blobstore:
          provider: s3
          options:
            access_key_id: ((cf_release_blobs_buckets_access_key_id))
            secret_access_key: ((cf_release_blobs_buckets_secrect_access_key))
  - put: cf-smoke-tests-release
    params:
      repository: cf-smoke-tests-release
      rebase: true

- name: claim-cats-pool
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: cf-smoke-tests-release-trigger
      trigger: true
    - get: cf-smoke-tests-release
  - put: cats-pool
    params:
      claim: cats

- name: deploy-updated-smokes
  serial: true
  public: true
  serial_groups: [smoke_tests]
  <<: *release_lock_if_not_success
  plan:
  - in_parallel:
    - get: cats-pool
      trigger: true
      passed: [claim-cats-pool]
    - get: runtime-ci
    - get: cf-deployment-concourse-tasks
    - get: cf-smoke-tests-release-trigger
      passed: [claim-cats-pool]
    - get: cf-smoke-tests-release
      passed: [claim-cats-pool]
    - get: relint-envs
    - get: windows2019-stemcell
  - task: upload-windows2019-stemcell
    file: runtime-ci/tasks/bosh-upload-stemcell/task.yml
    input_mapping:
      bbl-state: relint-envs
      stemcell: windows2019-stemcell
    params:
      BBL_STATE_DIR: environments/test/cats/bbl-state
  - task: deploy-smoke-tests-errand
    file: runtime-ci/tasks/bosh-deploy-smokes/task.yml
    input_mapping:
      bbl-state: relint-envs
    params:
      BBL_STATE_DIR: environments/test/cats/bbl-state
      SYSTEM_DOMAIN: cf.cats.env.wg-ard.ci.cloudfoundry.org
      CREDHUB_ENV_NAME: bosh-cats

- name: run-smokes-errand
  serial: true
  public: true
  serial_groups:
  - smoke_tests
  <<: *release_lock_if_not_success
  plan:
  - in_parallel:
    - get: cats-pool
      trigger: true
      passed: [deploy-updated-smokes]
    - get: cf-deployment-concourse-tasks
    - get: cf-smoke-tests-release-trigger
      passed: [deploy-updated-smokes]
    - get: cf-smoke-tests-release
      passed: [deploy-updated-smokes]
    - get: relint-envs
  - task: run-smokes
    file: cf-deployment-concourse-tasks/run-errand/task.yml
    input_mapping:
      bbl-state: relint-envs
    params:
      BBL_STATE_DIR: environments/test/cats/bbl-state
      DEPLOYMENT_NAME: cf-smoke-tests
      ERRAND_NAME: smoke_tests
  - task: run-smokes-windows
    file: cf-deployment-concourse-tasks/run-errand/task.yml
    input_mapping:
      bbl-state: relint-envs
    params:
      BBL_STATE_DIR: environments/test/cats/bbl-state
      DEPLOYMENT_NAME: cf-smoke-tests
      ERRAND_NAME: smoke_tests_windows

- name: delete-smokes-deployment
  serial: true
  public: true
  serial_groups: [smoke_tests]
  <<: *release_lock_if_not_success
  plan:
  - in_parallel:
    - get: cats-pool
      trigger: true
      passed: [run-smokes-errand]
    - get: cf-deployment-concourse-tasks
    - get: cf-smoke-tests-release-trigger
      passed: [run-smokes-errand]
    - get: cf-smoke-tests-release
      passed: [run-smokes-errand]
    - get: relint-envs
  - task: delete-smoke-tests-deployment
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    input_mapping:
      bbl-state: relint-envs
    params:
      BBL_STATE_DIR: environments/test/cats/bbl-state
      DEPLOYMENT_NAME: cf-smoke-tests

- name: create-final-release
  serial: true
  public: true
  <<: *release_lock_if_not_success
  plan:
  - in_parallel:
    - get: cats-pool
      trigger: true
      passed: [delete-smokes-deployment]
    - get: cf-smoke-tests-release-trigger
      passed: [delete-smokes-deployment]
      trigger: true
    - get: cf-smoke-tests-release
      passed: [delete-smokes-deployment]
    - get: cf-smoke-tests-version
    - get: runtime-ci
  - task: create-final-release
    file: runtime-ci/tasks/create-final-release/task.yml
    input_mapping:
      release-repo: cf-smoke-tests-release
      semantic-version: cf-smoke-tests-version
    params:
      BLOBS_BUCKET_ACCESS_KEY_ID: ((cf_release_blobs_buckets_access_key_id))
      BLOBS_BUCKET_SECRET_KEY: ((cf_release_blobs_buckets_secrect_access_key))
  - put: cf-smoke-tests-release
    params:
      repository: final-release-repo
      rebase: true
      tag: cf-smoke-tests-version/version
  - put: cf-smoke-tests-version
    params:
      bump: patch
  - *release_lock
